version: '3.9'

services:
  backend:
    build:
      context: ./fbi-backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./fbi-backend:/app
      - /app/node_modules 
    environment:
      - NODE_ENV=development
    command: npm run dev
